name: bot-telegram

networks:
  default:
    name: bot-telegram
    driver: bridge

services:
  webapp:
    container_name: webapp
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    networks:
      - default
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql
    image: mysql:8.4.6
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: asdasd
      MYSQL_DATABASE: testdb
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.2
    ports:
      - 8080:80
    networks:
      - default
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
