server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    location = /phpmyadmin {
        return 301 /phpmyadmin/;
    }

    location ^~ /phpmyadmin/ {
        alias /var/www/phpmyadmin/;
        index index.php;
        try_files $uri $uri/ /phpmyadmin/index.php?$args;

        location ~ ^/phpmyadmin/(.+\.php)$ {
            include fastcgi_params;
            fastcgi_pass phpmyadmin:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/$1;
        }
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass webapp:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
